### ISSUE TITLE
nfct_logger crashes on start up.

### ISSUE THREAD

**Issue by mellowcandle** [mk-fg/conntrack-logger#2]
./nfct_logger.py -p tcp
python: api.c:306: nfct_callback_register2: Assertion `h != ((void *)0)' failed.
Aborted (core dumped)

That's a permission issue. running with `sudo` solved the issue.
I suggest testing for the appropriate permissions and not crashing :)

**Comment by mk-fg** [comment]
Yeah, probably checking for NULL returned from one of the previous calls and getting strerror should suffice.
Thanks for reporting.

Haven't used the thing myself in a while, so it might be a bit neglected.

**Comment by mk-fg** [comment]
Hm, weird, running it as a user myself, seem to be getting something more proper:
```
% ./nfct_logger.py -p tcp
Traceback (most recent call last):
  File "./nfct_logger.py", line 211, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./nfct_logger.py", line 190, in main
    next(src)
  File "/home/fraggod/hatch/conntrack-logger/nfct_cffi.py", line 186, in generator
    self.libnfct.NFNL_SUBSYS_NONE, events, check_notnull=True )
  File "/home/fraggod/hatch/conntrack-logger/nfct_cffi.py", line 155, in <lambda>
    self.libnfct_cache[k] = lambda *a,**kw: self._ffi_call(func, a, **kw)
  File "/home/fraggod/hatch/conntrack-logger/nfct_cffi.py", line 147, in _ffi_call
    raise NFCTError(errno_, os.strerror(errno_))
nfct_cffi.NFCTError: [Errno 1] Operation not permitted
```

**Comment by mk-fg** [comment]
So what seem to be happening in your case is that `nfct_open()` actually returns NULL instead of "handle" pointer, which causes aforementioned assert to fail in `nfct_callback_register2()` (which is first line of that func), but result of `nfct_open()` is actually checked for NULL in python code, and raises that error in my case.

Guess that check somehow doesn't work in your case or something sets the thing to NULL between these lines, and I don't know how to reproduce it or what should be done here otherwise (i.e. what's there looks correct to me).

Checking for e.g. uid==0 is kinda bad, as that'd break if kernel actually allows access to netlink sockets for non-root (e.g. due to posix capability or some mac module) and for uid namespaces, where "root" is more like "regular user" from kernel's perspective.

So I'd leave it as it is, unless you (or anyone) has a better idea about what's happening here.
