### ISSUE TITLE
Failed to parse event data (on Ubuntu "Xenial" 16.04)

### ISSUE THREAD

**Issue by mpontillo** [mk-fg/conntrack-logger#4]
I see intermittent parse failures when I run this on Ubuntu 16.04, such as the following:

    ERROR:root:Failed to parse event data: <flow type="new"><meta direction="original"><layer3 protonum="2" protoname="ipv4"><src>192.168.0.2</src><dst>1.75.7.178</dst></layer3><layer4 protonum="6" protoname="tcp"><sport>33367</sport><dport>80</dport></layer4></meta><meta direction="reply"><layer3 protonum="2" protoname="ipv4"><src>1.75.7.178</src><dst>1.2.4.5</dst></layer3><layer4 protonum="6" protoname="tcp"><sport>80</sport><dport>33367</dport></layer4></meta><meta direction="independent"><state>SYN_SENT</state><timeout>120</timeout><id>501034516</id><unreplied/></meta><when><hour>21</hour><min>39</min><sec>50</sec><wday>3</wday><day>11</day><month>7</month><year>2017</year></when></flow>

I haven't had a chance to triage further; will update this issue if I do.

**Comment by mk-fg** [comment]
It's easy to debug such things by adding something like:

    ev_xml = ...
    print(parse_event(ev_xml))
    exit()

Right after parse_event() definition and running the script.

In this case, it's assertion for flows being symmetrical - having same src/dst between original/reply (but reversed for reply ofc) - that was failing, as you seem to have reply with different dst that original src ip.

I think I've had the check because I wasn't sure whether connection for this flow will have IP/port info from "original" or "reply" packet, to avoid any hidden ambiguity.
Fairly sure it's "original" though, so just commented it out in f2ddd0d, should probably work for that case above now.

As a side note, I haven't really used/needed the thing for a few years now, and linux had few new socket introspection interfaces added since then, so maybe there are better ways to get same info these days than checking /proc like this script does.

**Comment by mpontillo** [comment]
Yes, my flows aren't symmetrical because NAT is being used. (And, of course, the tool won't be able to find the process related to a flow initiated remotely.) But the latest code seems to fix it; thanks!

**Comment by mk-fg** [comment]
> And, of course, the tool won't be able to find the process related to a flow initiated remotely

It actually should, as you have connection to a local ip/port, and that info is all in there, just gotta pick correctly which port is local, and find pid associated with that.
Same as with locally-initiated flows.

And I think info in "original" should be fine for that, but if it doesn't work for you, maybe not.
You can probably tinker with --debug option and log how script looks-up the connection in e.g. /proc/net/tcp, and make it work quite easily, shouldn't be a hard problem at all.

**Comment by mk-fg** [comment]
That is, unless I completely misunderstand what you mean, and it's not about local pids at all :)

**Comment by mpontillo** [comment]
Sorry if I wasn't clear. I meant that it's possible that neither endpoint exists on the host running the script. For example, conntrack will track the connection for a remote host on my LAN initiating a connection to the internet via the host running the script. So in that case, it won't be possible to find a PID a local socket is bound to, because there isn't one. ;-)

**Comment by mk-fg** [comment]
Indeed, though for logging these you can actually use e.g. `conntrack -E` from conntrack-tools, this script is pretty much just that plus finding pid via /proc.
